spring:
  application:
    name: erp-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

server:
  port: 8081

app:
  bootstrap:
    admin:
      enabled: true
      login-id: admin
      employee-code: 0000
      password: admin
      name: System Admin
      role: HQ_ADMIN
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/forerp
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  secret:
    key: My-Franchise-ERP-Project-Secret-Key-Is-Very-Strong-And-Long-12345
---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

jwt:
  secret:
    key: ${JWT_SECRET_KEY}